### PR TITLE
Fix errors highlighted by akismet-react app

### PR DESCRIPTION
**Pull request by eoigal**
Dops-components repo is being used by the akismet-react repo but due to recent changes this repo is no longer compatible.

This PR will fix bugs found while trying to make the 2 repos compatible. The PR on akismet-react can be found [here](https://github.com/Automattic/akismet-react/pull/22).

### CODE REVIEW

**Comment by gravityrail** [comment]
Good catches.

**Comment by cfinke** [comment]
Can this get fixed and merged? akismet-react is unusable by anyone who doesn't already have a custom development workflow set up until these conflicts are resolved.

**Comment by ryelle** [comment]
Most of these issues have been merged in other PRs, the only remaining issues preventing Akismet from building are now addressed in #71

**Comment by eoigal** [comment]
Agree with @ryelle, this can be closed as any issue left should be addressed in #71

**Pull request closed without merging**
