### PR TITLE
Since @extend can't be used inside @media, include a @mixin instead

### PR DESCRIPTION
**Pull request by eliorivero**

### CODE REVIEW

**Comment by MichaelArestad** [comment]
We really need to get rid of Noticons. I would try to remove that and try a Dashicon equivalent. Other than that, looks good.

**Comment by zinigor** [comment]
@MichaelArestad @jeffgolenski can you please help out with moving this thing towards merging? Perhaps you know someone who can make it happen?

**Comment by MichaelArestad** [comment]
I still think Noticons should be removed. Also, we should keep it to one mixin per mixin file. I know the dops-components files aren't super organized (something broke somewhere when I started to organize them), but it's easier to maintain them and find them separately.

**Comment by enejb** [comment]
I think converting to noticons can be done in a different PR. Lets merge this!

**Comment by MichaelArestad** [comment]
Yep. Needs a rebase and then just merge!

**Pull request merged**
