### PR TITLE
TextInput: create Calypso style inputs

### PR DESCRIPTION
**Pull request by MichaelArestad**
These will ultimately replace the text input in components/forms.

To test, switch to `add/input-text` on `jetpack` then go to Writing Settings and look at Post by Email. https://github.com/Automattic/jetpack/pull/4717

image

### CODE REVIEW

**Comment by MichaelArestad** [comment]
It's worth noting that I pulled the component code from Calypso instead of the `dops-components` version as it was much simpler. @ryelle @gravityrail thoughts?

**Comment by eliorivero** [comment]
@MichaelArestad maybe we can use this [input+copy button](https://wpcalypso.wordpress.com/devdocs/design/clipboard-button-input) so users can quickly copy the address.

**Comment by MichaelArestad** [comment]
We definitely could, but I haven't ported that over yet. Will look into shortly.

**Comment by oskosk** [comment]
:shipit: 

*Note*: This new component introduces several warning if using React 0.15 because props are being passed loosely to HTML elements and React 15 is warning about them now. 

(We're not using it yet, but as I was testing this branch I forgot to get back to React 14.  I was working on a PR for removing those warnings ) 

image

I think it's fine if we merge this and then fix the issues on the branch I'm working on .

**Pull request merged**
